# Generated by Django 3.2.7 on 2021-10-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_zip_ to_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_status',
        ),
    ]
