# Generated by Django 3.2.8 on 2021-10-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_collection_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
    ]
