# Generated by Django 3.2.8 on 2021-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
