# Generated by Django 3.2.8 on 2021-10-23 09:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_taggeditem_object_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
